[package]
name = "ciana_rust"
version = "0.1.0"
authors = ["Hiroyuki HANO <onah@dwahan.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang = "0.23.0"


